<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>优优图书-在线浏览</title>
<script type="text/javascript" src="/uushop/js/jquery-1.8.3.js" ></script>
<script type="text/javascript" src="/uushop/js/global.js" ></script>
<link  rel="stylesheet" href="/uushop/css/global.css" />
<style type="text/css">
#online_view{
	width:916px;
	height:64px;
	padding:20px;
	border:2px solid #dbebbc;
}
.content #online_view{
	margin-bottom:10px;
}
#view_image{
	float:left;
}
#view_image img{
	width:160px; heigth:60px;
	overflow: hidden;
}
#view_name{
	width:220px; heigth:60px;
	overflow: hidden;
	float:left;
}
#view_name p{
	line-height: 60px;
	font-size:14px;
}
#view_content{
	width:340px; heigth:60px;
	overflow: hidden;
	float:left;
	text-align: left;
	color:#999;
}
#view_btn a{display:block;margin-left:26px;display:block;float:right;border:none;cursor:pointer;}
#view_btn a.goon{background:url(../images/bg_cart_pic.gif) repeat-x 0 -330px;width:120px;height:23px; border-radius:3px;color:#6e5e4f;text-align:center;display:block;line-height:25px; border:1px solid #d1cdca; margin: 18px 20px 0 0; overflow:hidden;}
#view_btn a.goon:hover { background-position:0 -355px;text-decoration:none;}
</style>
</head>
<body>
<jsp:include page="/share/header2.jsp" />
<!-- Content Start -->
<div class="content">

<div id="online_view">
	<div id="view_image"><img src="beautiful_logo.jpg"  width="160px" height="60px"/></div>
	<div id="view_name"><p>图书名称：Beautiful Code</p></div>
	<div id="view_content">In this unique work, leading computer scientists discuss how they found unusual, carefully designed solutions to difficult problems. 
	This book lets the reader look over the shoulder of major coding and design experts to see problems through their eyes.</div>
	<div id="view_btn"><a href="online_view.html?doc=beautifulcode.swf" target="_blank" class="goon">在线浏览</a></div>
</div>

<div id="online_view">
	<div id="view_image"><img src="zepto_logo.png"  width="160px" height="60px"/></div>
	<div id="view_name"><p>图书名称：Zepto教程</p></div>
	<div id="view_content">zepto.js是一个专为mobile WebKit浏览器(如：Safari和Chrome)而开发的一个JavaScript框架。 
它标榜自己在其简约的开发理念，能够帮助开发人员简单、快速地完成开发交付任务。更重要的是这个JS框架，是超轻量级的，只有5KB。
zepto.js的语法借鉴并且兼容jQuery。</div>
	<div id="view_btn"><a href="online_view.html?doc=zepto_HTML5.swf" target="_blank" class="goon">在线浏览</a></div>
</div>

<div id="online_view">
	<div id="view_image"><img src="jquery_logo.jpg"  width="160px" height="60px"/></div>
	<div id="view_name"><p>图书名称：jQuery教程</p></div>
	<div id="view_content">jQuery is a fast, small, and feature-rich JavaScript library.
	 It makes things like HTML document traversal and manipulation, event handling, animation, and Ajax much simpler with an easy-to-use API that works across a multitude of browsers.
	</div>
	<div id="view_btn"><a href="online_view.html?doc=jquery.swf" target="_blank" class="goon">在线浏览</a></div>
</div>

<div id="online_view">
	<div id="view_image"><img src="freemarker_logo.png"  width="160px" height="60px"/></div>
	<div id="view_name"><p>图书名称：freemarker教程</p></div>
	<div id="view_content">FreeMarker is a "template engine"; a generic tool to generate text output (anything from HTML to autogenerated source code) based on templates. It's a Java package, a class library for Java programmers. 
	It's not an application for end-users in itself</div>
	<div id="view_btn"><a href="online_view.html?doc=freemarker.swf" target="_blank" class="goon">在线浏览</a></div>
</div>

</div>
<!-- Content Start -->

<!-- footer Start -->
<jsp:include page="/share/footer.jsp" />
<!-- footer End -->
</body>
</html>
